In [95]:
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
from meteostat import Point, Daily

In [96]:
start = datetime(2022, 5, 1)
end = datetime(2022, 5, 31)
#my birthday is in May

In [106]:
location = Point(36.66528200, 116.99491700, 38.80)
#my birth city is Jinan,Shandong,China and latitude,36.66528200,Longitude:116.99491700, altitude:38.80,source from https://www.altitude-maps.com/city/43_316,Jinan,Shandong,China

In [107]:
data = Daily(location, start, end)
data = data.fetch()

In [108]:
data

            tavg  tmin  tmax  prcp  snow   wdir  wspd  wpgt    pres  tsun
time
2022-05-01  17.8  11.2  23.9   0.0   NaN  221.0  12.2   NaN  1016.6   NaN
2022-05-02  22.3  13.3  28.1   0.0   NaN   75.0   7.4   NaN  1014.9   NaN
2022-05-03  26.3  18.1  30.4   0.0   NaN  187.0  15.5   NaN  1013.1   NaN
2022-05-04  26.9  22.3  31.5   0.0   NaN  191.0  21.9   NaN  1009.3   NaN
2022-05-05  26.9  23.2  31.5   0.0   NaN  189.0  26.3   NaN  1007.1   NaN
2022-05-06  18.6  12.3  32.3   0.0   NaN  104.0  17.4   NaN  1012.0   NaN
2022-05-07  13.9  12.2  16.1   0.0   NaN   72.0  13.9   NaN  1022.0   NaN
2022-05-08  12.6  10.6  15.2   0.3   NaN   55.0   8.2   NaN  1021.0   NaN
2022-05-09  10.9  10.4  14.7  10.9   NaN   22.0   5.5   NaN  1020.6   NaN
2022-05-10  14.5   9.4  19.7   0.0   NaN  210.0   6.3   NaN  1014.2   NaN
2022-05-11  18.1  12.1  21.3   0.0   NaN   75.0   6.8   NaN  1016.0   NaN
2022-05-12  15.1  12.4  17.2   2.3   NaN   62.0   8.2   NaN  1014.7   NaN
2022-05-13  14.5  11.1  21.7   0.0   NaN   25.0   8.0   NaN  1015.1   NaN
2022-05-14  17.9  11.1  23.7   0.0   NaN  207.0   6.4   NaN  1017.1   NaN
2022-05-15  21.9  11.8  26.7   0.0   NaN  209.0   8.8   NaN  1016.0   NaN
2022-05-16  23.1  19.0  28.1   0.0   NaN  223.0   9.8   NaN  1009.7   NaN
2022-05-17  28.8  19.3  32.4   0.0   NaN  196.0  15.5   NaN  1007.1   NaN
2022-05-18  25.1  22.9  32.4   0.0   NaN  222.0  11.9   NaN  1011.6   NaN
2022-05-19  24.9  18.9  31.2   0.0   NaN  210.0   9.6   NaN  1013.1   NaN
2022-05-20  23.7  18.5  30.7   0.0   NaN  216.0   7.7   NaN  1011.0   NaN
2022-05-21  28.3  22.1  32.3   0.0   NaN  203.0  11.2   NaN  1008.2   NaN
2022-05-22  27.7  21.9  33.2   0.0   NaN  197.0  12.2   NaN  1006.4   NaN
2022-05-23  27.6  22.8  32.7   0.0   NaN  181.0   8.7   NaN  1007.7   NaN
2022-05-24  27.9  23.3  32.2   0.0   NaN  182.0  12.8   NaN  1008.8   NaN
2022-05-25  18.7  14.3  32.0   0.0   NaN   85.0  13.4   NaN  1010.9   NaN
2022-05-26  23.2  15.4  29.4   NaN   NaN  232.0   9.4   NaN  1009.3   NaN
2022-05-27  29.3  21.4  34.4   0.0   NaN  220.0  13.0   NaN  1003.3   NaN
2022-05-28  27.9  23.3  34.6   0.0   NaN  200.0  22.1   NaN   997.9   NaN
2022-05-29  24.3  19.0  34.6   0.0   NaN  170.0  21.1   NaN   997.9   NaN
2022-05-30  27.5  18.8  34.0   0.0   NaN  218.0  11.1   NaN  1006.0   NaN
2022-05-31  28.6  22.9  34.0   0.0   NaN  204.0  27.1   NaN  1001.5   NaN

In [100]:
T_base = 18
cdds = [max(temp - T_base, 0) for temp in data.tavg]

In [101]:
total_cdd = sum(cdds)

In [102]:
print("Total CDD:", total_cdd)

Total CDD: 163.60000000000002